# Welcome to the Cognition & Brain Dynamics lab! 

If you are reading this lab manual, you have likely just joined the lab recently so welcome! 

If you are a current member, please, frequently refer to it for updated contents and if you have suggestions for improvement or new stuff, please let the PIs know or bring it up during our next meeting!


**Team **

Joining a research team means contributing your critical thinking, your skills, and your diligence to the team, and the team helping you sharpen your thinking, acquire new skills and techniques and advance your work much further than you could have done on your own.

Every lab member plays a vital role in the functioning from undergraduate students to early career researchers, support staff, and principal investigators (PIs)!

Providing you with rules and procedures is to ensure that current efforts build on past successes and failures. Newbies should not need to re-invent anything, you should not be starting your experiments from scratch, but build on what previous researchers have already achieved.


**Who's who: **

Please check the lab's website for an up-to-date list of lab members:
https://brainthemind.com/team/
Should you not find yourself there or want to update your profile, please send a textsnippet/ photo to the PIs. 

**Permanent lab members:** 

**Virginie van Wassenhove, Principal investigator**, Research Director (equivalent DR), CEA

**Sophie Herbst, Junior PI**, Researcher (equivalent CR), CEA

**Leila Azizi, Research Engineer**, Inserm
