# Expectations

Generally, we expect every member of the team, no matter the level of training or duration of stay in the lab to respect the following guidelines:

**Team culture**

We work in a collegial, collaborative, and friendly atmosphere.

Asking others for support, providing support, caring about our colleagues’ matters, and behaving respectfully to everyone within and around the team at any time is key. Every team member, no matter the level of expertise is encouraged to speak up, ask questions, interact and contribute to the life of the team.

Diversity and multiculturality are pillars of science. They are indispensable for the healthy functioning of any team. We are aware that the (academic) world is far from free of discrimination, but we actively work towards awareness to, and elimination of, sexism, racism, or any other aspect of discrimination in our interactions. 

If there are any personal or inter-personal issues in the team, please speak to us about it. You can also confidentially approach [Vanna](giovanna.santoro@cea.fr) to discuss any problem, and [Isabelle Denghien](isabelle.denghien@cea.fr), who is the official referent person for personal safety including issues related to harassment, as well as the student representatives at the Unicog level, currently Christos-Nikolaos Zacharopoulos (PhDs) and Ana Flo (Post-Docs). 

You are here to join us in every aspect of the exciting endeavour to better understand the human brain and mind! We foster curiosity, enthusiasm, questioning, motivation, reading as much as one can, telling each other where we may be wrong, and learning what we do not know. Science thrives on lively discussions that constantly evolve, new insights, and constant adjustments in our thinking. 

The more team members contribute to  discussions (e.g. in team meetings), the better we'll become! 


**Scientific integrity**

We strive to improve our scientific methods and practice every day.

We ask you to do your best to prevent errors, double check your code and results, make sanity checks a rule, avoid common statistical fallacies, and take responsibility for your work. 

Checking your experimental protocols: timing or randomization errors cannot be corrected once the data has been recorded, and such error can result in a huge waste of everyone's time and of the PI's funding (e.g. bear in mind an MEG experiment costs ~ 30.000€). Hence, prior to conducting an experiment, make sure the code runs without errors, obsessively check the outputs of 1 or 2 pilot participants for timing, randomization, and task-related issues to be corrected.

Write clean and commented analysis code, check for errors, and include sanity checks in your analysis. Think carefully about your choices of analysis parameters and test several options. 

We strive to produce objective and reproducible results. Be aware of biases and common statistical fallacies like p-hacking (selecting one significant result out of many), confirmation bias, selective exclusion of participants and many others (see the bibliography section for references). 

Report results as they are, including null-findings. If we always knew the results of our experiments, there would be no point in doing them!

Errors happen. To all of us, over and over again. The first step is of course to try and prevent them, but when you come across one, act on it: check its impact, make sure appropriate corrections are applied, and report it to your collaborators as soon as you can.  


**Intellectual ownership and representation of the team**

Always acknowledge everyone who contributed to your work (including supervisors, engineers, post docs) on slides and reports. 

Anything that leaves the lab (written reports, presentations, abstracts) has to be shown to the supervisors and co-authors beforehand. You are responsible for leaving enough time for at least one round of revisions before the deadline on any work.

Cite all references you used and never copy sentences or passages from other people’s work, without explicitily acknowledging. Plagiarism will be sanctioned by your committee (worsen your grade up to leading to rejection of your work in bad cases) and the scientific community (rejection of your work with legal consequences in very bad cases). Plagiarism and intellectual dishonesty are a sure way to loose the trust and respect of your colleagues.


**Scientific outcomes**

Academic work (from midterm reports to final written theses) have to be approved by your supervisor before submission. If your supervisor does not get to read and approve before submission, your university or school will anyway require our confidential evaluation of your work. Ideally, we wish to continuously discuss your advances and the write up of your reports. Minimally, we wish to receive your Master reports 2 weeks before the deadline, and your PhD thesis, one month before the submission to your doctoral committee. Regarding the oral presentations, you are expected to rehearse in front of the team at least one week before the defense (you should rehearse a few times before your PhD defense ;-)

Conference abstracts (posters, talks) and proceedings: feel free to bring up opportunities to present your work in different  seek approval of all co-authors before submission, 

Peer-reviewed articles in international or national journals:


**Different stages of expertise**

To all students: 
All requirements of your university program (submission deadlines, requirements, admin) are fully your own responsibility.
All written work (including slides) need to be shown to the supervisors with sufficient time to apply corrections.
Documentation is key to preserve knowledge in the team, allows benefit from others' work and to make sure your own hard work will be passed on and benefit the following generations of students. 


*Master 1 students* 

This is likely your first hands-on encounter with the scientific method. You will go through all stages of a project, and take more autonomy throughout the process. 

You will test participants, analyze the data, interpret and present the results. 
We encourage you to take over all those aspects as early as possible. 
We expect you to master the related literature and contribute to the improvement of the experimental design. 
We do not expect you to be fluent in programming, but you will have to learn to understand and modify code, and eventually write your own. You are in charge of documenting your work. 


*Master 2 students* 

You will go through all stages of a scientific project, including narrowing down the question, preparing the experimental protocol, data acquisition and analysis. 
Depending on the project, this might include several behavioral pilot experiments and/or data M/EEG acquisition and/or analysis. 

The direction of your work will be pre-defined by your advisors, but you are expected to contribute also to the theoretical aspects and implementation.
We expect you to take over responsibility for your study as early as possible, 
to master the relevant literature, and be the expert concerning all technical details as well as for the documentation of your work. You will likely be responsible for testing participants, and you will definitely analyze data and interpret the results. 
We do not expect you to be fully fluent in programming, but you will have to learn efficiently to eventually write your own. 


*PhD students* 

You will conduct all stages of the project, including narrowing down the initial question and building up on it, preparing the experimental protocols, data acquisitions and analyses. Hence, as a PhD student, you become the major driving force of the scientific work, which means you are responsible for the mastery of the literature, all technical details of your studies, the testing of participants, the analysis of the data, their interpretation, communication, etc... 

The direction of your work will be initially construed with your advisors, but you are progressively expected to rise to intellectual autonomy, both theoretically and empirically! In fact, you should become the best expert in the team on your own topic. If all goes well, you will get to start working in collaboration with the master students and start learning how to transmit the how tos, work solo but also in a team. 

__You are in charge of documenting your work.__


**What you can expect from us:**

- guidance at all stages of your project: from the initial question, to the paradigmatic approach, relevant literature, etc
- help you reach reasonably working code, help with debugging, tipps for sanity checks
- analysis feedback
- discussions, brainstorming, and interpretations of your results
- feedback on your presentations, training in front of the group (slides)
- thorough rounds of revision on written work (reports, and especially papers)
- weekly one-to-one meetings (more if needed, less if needed)
- weekly group meetings to gather more feedback
- a scientific work environment where you will hear and learn about various topics and questions
